"""empty message

Revision ID: 50aeea48d3b6
Revises: 8f6ef0166b33
Create Date: 2024-11-26 00:50:36.063769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50aeea48d3b6'
down_revision = '8f6ef0166b33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Card_Version', schema=None) as batch_op:
        batch_op.alter_column('card_type',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.String(length=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Card_Version', schema=None) as batch_op:
        batch_op.alter_column('card_type',
               existing_type=sa.String(length=2),
               type_=sa.VARCHAR(length=3),
               existing_nullable=False)

    # ### end Alembic commands ###
