"""empty message

Revision ID: 8f6ef0166b33
Revises: 6c0bca759ab1
Create Date: 2024-11-15 06:55:17.212122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f6ef0166b33'
down_revision = '6c0bca759ab1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login_status', sa.Boolean()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('login_status')

    # ### end Alembic commands ###
